name: Cloud Build Jar and Pack

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Locate pom.xml and Build Plugin
      run: |
        POM_PATH=$(find . -name "pom.xml" | head -n 1)
        if [ -z "$POM_PATH" ]; then
          echo "ERROR: pom.xml not found!"
          exit 1
        fi
        DIR_PATH=$(dirname "$POM_PATH")
        cd "$DIR_PATH"
        mvn clean package -DskipTests

    - name: Pack Resource Pack
      run: |
        zip -r SkyBattleResourcePack.zip pack.mcmeta assets/

    - name: Upload Finished JAR
      uses: actions/upload-artifact@v4
      with:
        name: SkyBattlePlugin
        path: '**/target/*.jar'

    - name: Upload Resource Pack
      uses: actions/upload-artifact@v4
      with:
        name: SkyBattleResourcePack
        path: SkyBattleResourcePack.zip

